import mongoose from 'mongoose';
import Deck from '../models/deckModel.js';

const mongoURI = 'mongodb://127.0.0.1/flashcards';
mongoose
  .connect(mongoURI)
  .then(() => console.log('Connected to MongoDB'))
  .then(
    Deck.create({
      name: 'Country Capitals',
      description: 'All the countries of the world and their capitals',
      cards: [
        { front: 'Abkhazia', back: 'Sukhumi' },
        { front: 'Afghanistan', back: 'Kabul' },
        { front: 'Akrotiri and Dhekelia', back: 'Episkopi Cantonment' },
        { front: 'Albania', back: 'Tirana' },
        { front: 'Algeria', back: 'Algiers' },
        { front: 'American Samoa', back: 'Pago Pago' },
        { front: 'Andorra', back: 'Andorra la Vella' },
        { front: 'Angola', back: 'Luanda' },
        { front: 'Anguilla', back: 'The Valley' },
        { front: 'Antigua and Barbuda', back: "St. John's" },
        { front: 'Argentina', back: 'Buenos Aires' },
        { front: 'Armenia', back: 'Yerevan' },
        { front: 'Aruba', back: 'Oranjestad' },
        { front: 'Ascension Island', back: 'Georgetown' },
        { front: 'Australia', back: 'Canberra' },
        { front: 'Austria', back: 'Vienna' },
        { front: 'Azerbaijan', back: 'Baku' },
        { front: 'Bahamas', back: 'Nassau' },
        { front: 'Bahrain', back: 'Manama' },
        { front: 'Bangladesh', back: 'Dhaka' },
        { front: 'Barbados', back: 'Bridgetown' },
        { front: 'Belarus', back: 'Minsk' },
        { front: 'Belgium', back: 'Brussels' },
        { front: 'Belize', back: 'Belmopan' },
        { front: 'Benin', back: 'Porto-Novo' },
        { front: 'Bermuda', back: 'Hamilton' },
        { front: 'Bhutan', back: 'Thimphu' },
        { front: 'Bolivia', back: 'Sucre' },
        { front: 'Bolivia', back: 'La Paz' },
        { front: 'Bosnia and Herzegovina', back: 'Sarajevo' },
        { front: 'Botswana', back: 'Gaborone' },
        { front: 'Brazil', back: 'Brasília' },
        { front: 'British Virgin Islands', back: 'Road Town' },
        { front: 'Brunei', back: 'Bandar Seri Begawan' },
        { front: 'Bulgaria', back: 'Sofia' },
        { front: 'Burkina Faso', back: 'Ouagadougou' },
        { front: 'Burundi', back: 'Bujumbura' },
        { front: 'Cambodia', back: 'Phnom Penh' },
        { front: 'Cameroon', back: 'Yaoundé' },
        { front: 'Canada', back: 'Ottawa' },
        { front: 'Cape Verde', back: 'Praia' },
        { front: 'Cayman Islands', back: 'George Town' },
        { front: 'Central African Republic', back: 'Bangui' },
        { front: 'Chad', back: "N'Djamena" },
        { front: 'Chile', back: 'Santiago' },
        { front: 'China', back: 'Beijing' },
        { front: 'Christmas Island', back: 'Flying Fish Cove' },
        { front: 'Cocos (Keeling) Islands', back: 'West Island' },
        { front: 'Colombia', back: 'Bogotá' },
        { front: 'Comoros', back: 'Moroni' },
        { front: 'Cook Islands', back: 'Avarua' },
        { front: 'Costa Rica', back: 'San José' },
        { front: 'Croatia', back: 'Zagreb' },
        { front: 'Cuba', back: 'Havana' },
        { front: 'Curaçao', back: 'Willemstad' },
        { front: 'Cyprus', back: 'Nicosia' },
        { front: 'Czech Republic', back: 'Prague' },
        { front: "Côte d'Ivoire", back: 'Yamoussoukro' },
        { front: 'Democratic Republic of the Congo', back: 'Kinshasa' },
        { front: 'Denmark', back: 'Copenhagen' },
        { front: 'Djibouti', back: 'Djibouti' },
        { front: 'Dominica', back: 'Roseau' },
        { front: 'Dominican Republic', back: 'Santo Domingo' },
        { front: 'East Timor (Timor-Leste)', back: 'Dili' },
        { front: 'Easter Island', back: 'Hanga Roa' },
        { front: 'Ecuador', back: 'Quito' },
        { front: 'Egypt', back: 'Cairo' },
        { front: 'El Salvador', back: 'San Salvador' },
        { front: 'Equatorial Guinea', back: 'Malabo' },
        { front: 'Eritrea', back: 'Asmara' },
        { front: 'Estonia', back: 'Tallinn' },
        { front: 'Ethiopia', back: 'Addis Ababa' },
        { front: 'Falkland Islands', back: 'Stanley' },
        { front: 'Faroe Islands', back: 'Tórshavn' },
        { front: 'Federated States of Micronesia', back: 'Palikir' },
        { front: 'Fiji', back: 'Suva' },
        { front: 'Finland', back: 'Helsinki' },
        { front: 'France', back: 'Paris' },
        { front: 'French Guiana', back: 'Cayenne' },
        { front: 'French Polynesia', back: 'Papeete' },
        { front: 'Gabon', back: 'Libreville' },
        { front: 'Gambia', back: 'Banjul' },
        { front: 'Georgia', back: 'Tbilisi' },
        { front: 'Germany', back: 'Berlin' },
        { front: 'Ghana', back: 'Accra' },
        { front: 'Gibraltar', back: 'Gibraltar' },
        { front: 'Greece', back: 'Athens' },
        { front: 'Greenland', back: 'Nuuk' },
        { front: 'Grenada', back: "St. George's" },
        { front: 'Guam', back: 'Hagåtña' },
        { front: 'Guatemala', back: 'Guatemala City' },
        { front: 'Guernsey', back: 'St. Peter Port' },
        { front: 'Guinea', back: 'Conakry' },
        { front: 'Guinea-Bissau', back: 'Bissau' },
        { front: 'Guyana', back: 'Georgetown' },
        { front: 'Haiti', back: 'Port-au-Prince' },
        { front: 'Honduras', back: 'Tegucigalpa' },
        { front: 'Hungary', back: 'Budapest' },
        { front: 'Iceland', back: 'Reykjavík' },
        { front: 'India', back: 'New Delhi' },
        { front: 'Indonesia', back: 'Jakarta' },
        { front: 'Iran', back: 'Tehran' },
        { front: 'Iraq', back: 'Baghdad' },
        { front: 'Ireland', back: 'Dublin' },
        { front: 'Isle of Man', back: 'Douglas' },
        { front: 'Israel', back: 'Jerusalem' },
        { front: 'Italy', back: 'Rome' },
        { front: 'Jamaica', back: 'Kingston' },
        { front: 'Japan', back: 'Tokyo' },
        { front: 'Jersey', back: 'St. Helier' },
        { front: 'Jordan', back: 'Amman' },
        { front: 'Kazakhstan', back: 'Astana' },
        { front: 'Kenya', back: 'Nairobi' },
        { front: 'Kiribati', back: 'Tarawa' },
        { front: 'Kosovo', back: 'Pristina' },
        { front: 'Kuwait', back: 'Kuwait City' },
        { front: 'Kyrgyzstan', back: 'Bishkek' },
        { front: 'Laos', back: 'Vientiane' },
        { front: 'Latvia', back: 'Riga' },
        { front: 'Lebanon', back: 'Beirut' },
        { front: 'Lesotho', back: 'Maseru' },
        { front: 'Liberia', back: 'Monrovia' },
        { front: 'Libya', back: 'Tripoli' },
        { front: 'Liechtenstein', back: 'Vaduz' },
        { front: 'Lithuania', back: 'Vilnius' },
        { front: 'Luxembourg', back: 'Luxembourg' },
        { front: 'Macedonia', back: 'Skopje' },
        { front: 'Madagascar', back: 'Antananarivo' },
        { front: 'Malawi', back: 'Lilongwe' },
        { front: 'Malaysia', back: 'Kuala Lumpur' },
        { front: 'Maldives', back: 'Malé' },
        { front: 'Mali', back: 'Bamako' },
        { front: 'Malta', back: 'Valletta' },
        { front: 'Marshall Islands', back: 'Majuro' },
        { front: 'Mauritania', back: 'Nouakchott' },
        { front: 'Mauritius', back: 'Port Louis' },
        { front: 'Mexico', back: 'Mexico City' },
        { front: 'Moldova', back: 'Chisinau' },
        { front: 'Monaco', back: 'Monaco' },
        { front: 'Mongolia', back: 'Ulaanbaatar' },
        { front: 'Montenegro', back: 'Podgorica' },
        { front: 'Montserrat', back: 'Plymouth' },
        { front: 'Morocco', back: 'Rabat' },
        { front: 'Mozambique', back: 'Maputo' },
        { front: 'Myanmar', back: 'Naypyidaw' },
        { front: 'Nagorno-Karabakh Republic', back: 'Stepanakert' },
        { front: 'Namibia', back: 'Windhoek' },
        { front: 'Nauru', back: 'Yaren' },
        { front: 'Nepal', back: 'Kathmandu' },
        { front: 'Netherlands', back: 'Amsterdam' },
        { front: 'New Caledonia', back: 'Nouméa' },
        { front: 'New Zealand', back: 'Wellington' },
        { front: 'Nicaragua', back: 'Managua' },
        { front: 'Niger', back: 'Niamey' },
        { front: 'Nigeria', back: 'Abuja' },
        { front: 'Niue', back: 'Alofi' },
        { front: 'Norfolk Island', back: 'Kingston' },
        { front: 'North Korea', back: 'Pyongyang' },
        { front: 'Northern Cyprus', back: 'Nicosia' },
        { front: 'United Kingdom Northern Ireland', back: 'Belfast' },
        { front: 'Northern Mariana Islands', back: 'Saipan' },
        { front: 'Norway', back: 'Oslo' },
        { front: 'Oman', back: 'Muscat' },
        { front: 'Pakistan', back: 'Islamabad' },
        { front: 'Palau', back: 'Ngerulmud' },
        { front: 'Palestine', back: 'Jerusalem' },
        { front: 'Panama', back: 'Panama City' },
        { front: 'Papua New Guinea', back: 'Port Moresby' },
        { front: 'Paraguay', back: 'Asunción' },
        { front: 'Peru', back: 'Lima' },
        { front: 'Philippines', back: 'Manila' },
        { front: 'Pitcairn Islands', back: 'Adamstown' },
        { front: 'Poland', back: 'Warsaw' },
        { front: 'Portugal', back: 'Lisbon' },
        { front: 'Puerto Rico', back: 'San Juan' },
        { front: 'Qatar', back: 'Doha' },
        { front: 'Republic of China (Taiwan)', back: 'Taipei' },
        { front: 'Republic of the Congo', back: 'Brazzaville' },
        { front: 'Romania', back: 'Bucharest' },
        { front: 'Russia', back: 'Moscow' },
        { front: 'Rwanda', back: 'Kigali' },
        { front: 'Saint Barthélemy', back: 'Gustavia' },
        { front: 'Saint Helena', back: 'Jamestown' },
        { front: 'Saint Kitts and Nevis', back: 'Basseterre' },
        { front: 'Saint Lucia', back: 'Castries' },
        { front: 'Saint Martin', back: 'Marigot' },
        { front: 'Saint Pierre and Miquelon', back: 'St. Pierre' },
        { front: 'Saint Vincent and the Grenadines', back: 'Kingstown' },
        { front: 'Samoa', back: 'Apia' },
        { front: 'San Marino', back: 'San Marino' },
        { front: 'Saudi Arabia', back: 'Riyadh' },
        { front: 'Scotland', back: 'Edinburgh' },
        { front: 'Senegal', back: 'Dakar' },
        { front: 'Serbia', back: 'Belgrade' },
        { front: 'Seychelles', back: 'Victoria' },
        { front: 'Sierra Leone', back: 'Freetown' },
        { front: 'Singapore', back: 'Singapore' },
        { front: 'Sint Maarten', back: 'Philipsburg' },
        { front: 'Slovakia', back: 'Bratislava' },
        { front: 'Slovenia', back: 'Ljubljana' },
        { front: 'Solomon Islands', back: 'Honiara' },
        { front: 'Somalia', back: 'Mogadishu' },
        { front: 'Somaliland', back: 'Hargeisa' },
        { front: 'South Africa', back: 'Pretoria' },
        {
          front: 'South Georgia and the South Sandwich Islands',
          back: 'Grytviken',
        },
        { front: 'South Korea', back: 'Seoul' },
        { front: 'South Ossetia', back: 'Tskhinvali' },
        { front: 'South Sudan', back: 'Juba' },
        { front: 'Spain', back: 'Madrid' },
        { front: 'Sri Lanka', back: 'Sri Jayawardenapura Kotte' },
        { front: 'Sudan', back: 'Khartoum' },
        { front: 'Suriname', back: 'Paramaribo' },
        { front: 'Swaziland', back: 'Mbabane' },
        { front: 'Sweden', back: 'Stockholm' },
        { front: 'Switzerland', back: 'Bern' },
        { front: 'Syria', back: 'Damascus' },
        { front: 'São Tomé and Príncipe', back: 'São Tomé' },
        { front: 'Tajikistan', back: 'Dushanbe' },
        { front: 'Tanzania', back: 'Dodoma' },
        { front: 'Thailand', back: 'Bangkok' },
        { front: 'Togo', back: 'Lomé' },
        { front: 'Tonga', back: 'Nukuʻalofa' },
        { front: 'Transnistria', back: 'Tiraspol' },
        { front: 'Trinidad and Tobago', back: 'Port of Spain' },
        { front: 'Tristan da Cunha', back: 'Edinburgh of the Seven Seas' },
        { front: 'Tunisia', back: 'Tunis' },
        { front: 'Turkey', back: 'Ankara' },
        { front: 'Turkmenistan', back: 'Ashgabat' },
        { front: 'Turks and Caicos Islands', back: 'Cockburn Town' },
        { front: 'Tuvalu', back: 'Funafuti' },
        { front: 'Uganda', back: 'Kampala' },
        { front: 'Ukraine', back: 'Kiev' },
        { front: 'United Arab Emirates', back: 'Abu Dhabi' },
        { front: 'United Kingdom; England', back: 'London' },
        { front: 'United States', back: 'Washington, D.C.' },
        { front: 'United States Virgin Islands', back: 'Charlotte Amalie' },
        { front: 'Uruguay', back: 'Montevideo' },
        { front: 'Uzbekistan', back: 'Tashkent' },
        { front: 'Vanuatu', back: 'Port Vila' },
        { front: 'Vatican City', back: 'Vatican City' },
        { front: 'Venezuela', back: 'Caracas' },
        { front: 'Vietnam', back: 'Hanoi' },
        { front: 'Wales', back: 'Cardiff' },
        { front: 'Wallis and Futuna', back: 'Mata-Utu' },
        { front: 'Western Sahara', back: 'El Aaiún' },
        { front: 'Yemen', back: 'Sanaá' },
        { front: 'Zambia', back: 'Lusaka' },
        { front: 'Zimbabwe', back: 'Harare' },
      ],
    }).then((data) => console.log(data))
  );
